# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_radius', models.IntegerField()),
                ('choice_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('choice_colour', models.CharField(default='#377eb8', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('map_center_lon', models.FloatField()),
                ('map_center_lat', models.FloatField()),
                ('map_center_radius', models.FloatField()),
                ('map_center_zoom', models.FloatField()),
                ('map_polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomap.Map'),
        ),
    ]
