# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_center_zoom',
            field=models.FloatField(default=14),
            preserve_default=False,
        ),
    ]
