# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 15, 51, 4, 43630, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
