# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0002_event_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Default', max_length=800),
            preserve_default=False,
        ),
    ]
