# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0002_map_map_center_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_center',
        ),
    ]
