# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0003_remove_map_map_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
