# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomap', '0005_auto_20160111_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statType', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('zoom', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
