# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='dataSource',
            new_name='feedback1',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='generalFeedback',
            new_name='feedback2',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='problem',
            new_name='feedback3',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback5',
            field=models.TextField(blank=True),
        ),
    ]
