# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0009_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
