# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0011_auto_20160115_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventType_mainCategory',
            new_name='eventType',
        ),
    ]
