# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0013_auto_20160115_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType_subCategory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
