# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0014_auto_20160115_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType_subCategory',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
